export type BlogPost = {
  slug: string
  title: string
  label: string
  excerpt: string
  author: string
  published: string
  updated: string
  canonicalUrl: string
  blocks: string[]
}

const eligibilityCta = [
  '## Interested in an eligibility review?',
  'The original Local Infusion article closed by inviting readers into its infusion centers, private suites, infusion guides, and physician-referral onboarding. Those services belong to Local Infusion. Local Doctor does not operate infusion centers.',
  'If you want to know whether a specialist review of Alzheimer\'s treatment eligibility may be useful, [[start with a short intake|/get-started]]. A licensed clinician still has to decide whether any testing or treatment is appropriate.',
]

export const blogPosts: BlogPost[] = [
  {
    slug: 'diet-for-alzheimers-patients',
    title: 'Diet For Alzheimer\'s Patients: Foods To Eat & Avoid',
    label: 'Brain health',
    excerpt: 'The science behind what foods to eat and avoid so patients and their caregivers can feel empowered to make the healthiest choices.',
    author: 'Ashley Knapp, RN',
    published: '2024-01-16',
    updated: '2024-11-10',
    canonicalUrl: 'https://mylocalinfusion.com/diet-for-alzheimers-patients/',
    blocks: [
      'The science behind what foods to eat and avoid so patients and their caregivers can feel empowered to make the healthiest choices.',
      'Alzheimer\'s disease — the most common cause of dementia — is a neurodegenerative disease that affects a person\'s memory and thinking skills. It causes physical changes to the brain cells, resulting in the buildup of amyloid plaques and bundles of fibers called neurofibrillary tangles (i.e. abnormal bundles of tau proteins). These plaques and tangles in the brain result in a loss of connections between neurons. Since the neurons are responsible for transmitting messages as they die, Alzheimer\'s patients experience memory loss, confusion, and difficulty carrying out tasks. While there is no cure for Alzheimer\'s, a healthy diet can help support a patient\'s brain and body. Below, we dive into the science behind what foods to eat and avoid so patients and their caregivers can feel empowered to make the healthiest choices.',
      '## The best diet for Alzheimer\'s patients',
      'MIND diet is an acronym for Mediterranean-DASH Intervention for Neurodegenerative Delay. It is a mix of the Mediterranean diet and the DASH diet (Dietary Approaches to Stop Hypertension). The focus: food choices that lower blood pressure and have been proven to benefit brain health.',
      'It focuses on plant-based foods with a reduced consumption of animal products, as well as foods rich in saturated fat. The emphasis is on plants, with a high consumption of berries and green leafy vegetables.',
      'According to [[research conducted on over 900 dementia-free older adults|https://pubmed.ncbi.nlm.nih.gov/25681666/]], it was found that following the MIND diet resulted in a [[reduced risk of Alzheimer\'s|https://pubmed.ncbi.nlm.nih.gov/25681666/]] and a [[slower rate of cognitive decline|https://pubmed.ncbi.nlm.nih.gov/26086182/]]. Also, an intensive analysis of the MIND diet and other factors found that adhering to it for about 4.5 years [[reduced the rate of Alzheimer\'s disease by 53%|https://www.ncbi.nlm.nih.gov/pubmed/25681666]] compared to when it wasn\'t adhered to.',
      'One of the reasons why the MIND diet has so many benefits for Alzheimer\'s patients is the rich antioxidants in the food groups recommended. The antioxidants in berries and the vitamin E in olive oil, leafy greens, avocados, and nuts [[can help protect the brain from oxidative stress|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2805706/]], which refers to the imbalance between the production of antioxidant defenses and free radicals. Long-term exposure to oxidative stress can result in cell damage, especially in the brain.',
      'Another reason is their anti-inflammatory effect. While inflammation is the body\'s natural response to infections and injuries, it can be harmful in excess. When not properly regulated, inflammation [[can contribute to chronic disease|https://www.ncbi.nlm.nih.gov/books/NBK493173/]]. Omega-3 fatty acids have anti-inflammatory effects on the brain, and their consumption [[is associated with slower loss of brain function|https://pubmed.ncbi.nlm.nih.gov/27633106/]].',
      'There are several brain-healthy food groups included in the MIND diet:',
      '### Green leafy vegetables',
      'Vegetables like kale, spinach, collard greens, and lettuce [[help with age-related cognitive decline|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5772164/]]. They [[help lower inflammation and oxidative stress|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5772164/]], both of which are [[associated with Alzheimer\'s disease|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC2676354/]]. It\'s recommended that, while on this diet, patients consume [[greater than or equal to 6 servings of leafy green vegetables per week|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7199507/#R27]].',
      '### Nuts',
      'Cashews, almonds, and pistachios are great snacks for the brain because they contain fiber, antioxidants, and healthy fats. On this diet, Alzheimer\'s patients should consume [[greater than or equal to 5 servings of nuts per week|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7199507/#R30]].',
      '### Berries',
      'According to recent studies, consuming berries such as blackberries, strawberries, raspberries, and blueberries [[can prevent cognitive aging in women by up to 2.5 years|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3582325/]]. Consuming more than or equal to 2 servings of berries per week is recommended.',
      '### Beans',
      'Beans such as black beans, pinto beans, and kidney beans are low in calories and fat and high in protein and fiber. It\'s suggested that they have [[more than 3 servings per week|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC7199507/#R30]].',
      '### Whole grains',
      'Grains like brown rice, oatmeal, whole grain pasta, and quinoa are great for the brain. The MIND diet [[recommends the consumption of more than or equal to 3 servings of whole grains per day|https://pubmed.ncbi.nlm.nih.gov/24047922]].',
      '### Fish',
      'Fish included on the MIND diet are salmon, tuna, and trout, all of which contain healthy fats. Researchers [[found that eating fish at least once a week helps protect brain function|https://pubmed.ncbi.nlm.nih.gov/16216930]].',
      '### Poultry',
      'Poultry like chicken, turkey, and eggs are healthy brain foods. Consumption of eggs, for example, [[is associated with better performance in memory function and verbal fluency|https://pubmed.ncbi.nlm.nih.gov/31360988/]]. Also, eggs in the diet [[result in better performance in cognitive tests|https://pubmed.ncbi.nlm.nih.gov/31360988/]]. Patients are to consume [[more than or equal to 2 servings of poultry per week|https://pubmed.ncbi.nlm.nih.gov/22449789/]].',
      '### Olive oil',
      'A study [[found that using olive oil as your primary oil at home provides better protection against cognitive decline|https://pubmed.ncbi.nlm.nih.gov/19707219/]] and other risk factors like obesity and heart disease.',
      '## A note on the Mediterranean diet',
      'Closely related to MIND, the Mediterranean diet focuses on the traditional foods of countries bordering the Mediterranean Sea and is celebrated as a long-term approach to healthy eating. It emphasizes the consumption of nuts and seeds, whole grains, fruits, legumes, and vegetables.',
      'In [[a 2018 study|https://www.ncbi.nlm.nih.gov/pubmed/29574441]], researchers found that those who followed this diet had thicker cortical brain regions (in Alzheimer\'s patients, these brain regions shrink). Also, Alzheimer\'s patients have a higher level of beta-amyloid protein and lower glucose metabolism, but following the Mediterranean diet may result in [[higher glucose metabolism and lower levels of beta-amyloid protein|https://www.ncbi.nlm.nih.gov/pubmed/29653991]].',
      'A new study, which examined about 600 brains of older people who died at 91, [[found that people who stuck to either the Mediterranean or MIND diet had less evidence of pathologies like tau tangles and amyloid plaques|https://pubmed.ncbi.nlm.nih.gov/36889921/]].',
      '## Foods that should be avoided with Alzheimer\'s',
      'The MIND diet specifically [[limits some foods|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC4532650/]], including:',
      '- Red meat',
      '- Butter and margarine',
      '- Cheese',
      '- Pastries and sweets',
      '- Fried or fast food',
      'It\'s important to avoid a high-fat diet with excess saturated fatty acids (SFA) and cholesterol, as they can [[contribute to the progression of Alzheimer\'s disease|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9656789/#B18-nutrients-14-04564]]. Also, this type of diet is related to hyper-insulinemia, [[which may result in a higher risk of Alzheimer\'s disease|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9656789/#B21-nutrients-14-04564]].',
      'The original article also noted that on January 6, 2023, Leqembi received full FDA approval through the Accelerated Approval pathway for the treatment of Alzheimer\'s, making it one of the few infusions that can be used for this disease, and that Local Infusion was ready to offer it at its locations once a patient was referred. Local Doctor does not operate those centers. Read [[Leqembi (Lecanemab) Is Now Approved For Alzheimer\'s Treatment: What To Know|/blog/leqembi-infusion]].',
      ...eligibilityCta,
    ],
  },
  {
    slug: 'leqembi-lecanemab-cost',
    title: 'How Much Does Leqembi (Lecanemab) Cost?',
    label: 'Cost',
    excerpt: 'How much infusions of this Alzheimer\'s drug cost (with and without insurance), and how patients can lower the cost.',
    author: 'Jenna Paladino, NP',
    published: '2023-09-21',
    updated: '2024-11-10',
    canonicalUrl: 'https://mylocalinfusion.com/leqembi-lecanemab-cost/',
    blocks: [
      'How much infusions of this new Alzheimer\'s drug cost (with and without insurance) and how patients can lower the cost.',
      'Leqembi is an intravenous (IV) infusion prescribed for early Alzheimer\'s disease that belongs to the amyloid beta-directed monoclonal antibody drug class. It contains the active drug lecanemab-irmb and is used to slow the progression of Alzheimer\'s disease in patients who have mild cognitive impairment or mild dementia — meaning those who are still in the early stages of dementia or who are experiencing some cognitive defects that do not significantly impair their daily lives. On January 6, 2023, Leqembi received full approval from the US Food and Drug Administration through the Accelerated Approval pathway for the treatment of Alzheimer\'s disease. It joined the new wave of medications that targets the fundamental pathophysiology of Alzheimer\'s disease and have received traditional approval, including Aduhelm (aducanumab). Leqembi [[works by reducing amyloid plaques|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10040446]] in the brain which, in turn, slows down the progression of cognitive decline associated with Alzheimer\'s disease.',
      'Following its successful clinical trial and FDA approval, the original article reports that Local Infusion became the first center in Maine to administer Leqembi and was ready to offer it at Local Infusion locations once a patient was referred by a clinician. Local Doctor does not operate infusion centers. Below is that article\'s breakdown of how much infusions of this Alzheimer\'s drug cost (with and without insurance), along with how patients and caregivers can lower the cost if they decide to proceed with this treatment option.',
      '## How much does Leqembi (lecanemab) cost?',
      'Leqembi, which is produced by Eisai Inc and Biogen Inc., has a [[list price of $26,500 per year|https://media-us.eisai.com/2023-01-06-EISAIS-APPROACH-TO-U-S-PRICING-FOR-LEQEMBI-TM-LECANEMAB-,-A-TREATMENT-FOR-EARLY-ALZHEIMERS-DISEASE,-SETS-FORTH-OUR-CONCEPT-OF-SOCIETAL-VALUE-OF-MEDICINE-IN-RELATION-TO-PRICE-OF-MEDICINE]]. However, the actual out-of-pocket amount each patient pays will vary depending on their individual insurance coverage. Be sure to ask about co-pay assistance programs through Eisai if cost is of concern — many patients will qualify for additional assistance and even $0 copay depending on eligibility.',
      '## How does insurance coverage impact drug pricing?',
      'How much the patient pays (aka out-of-pocket costs) is ultimately a function of the insurance plan. Every plan is different and has different premiums, but there are a few concepts that are important to remember:',
      '- Copay: a fixed amount of money that you pay for a healthcare service, which generally totals $0-$50 per visit',
      '- Coinsurance: a percentage of the total cost of a healthcare service',
      '- Deductible: an amount of money you must pay before your health insurance plan starts to share costs',
      '- Or a combination of these options',
      '[[Eisai estimates|https://www.eisai.com/news/2023/news202302.html]] that roughly 91% of patients will be covered through Medicare with Medigap (supplemental insurance), Medicare Advantage, Medicaid, or Commercial insurance, thus reducing their care costs to $0 or a few dollars per day. The remaining 9% of patients will be responsible for 20% of Leqembi costs as co-insurance under Medicare Part B, paying $26,500 per year (or roughly $14.50 per day). Don\'t have insurance or aren\'t in-network with your infusion center? It may be possible to bill your insurance company for the medication costs out-of-network. If out-of-network benefits aren\'t available, you may be able to be seen as a self-pay patient.',
      '## How does site of care impact the cost of Leqembi (lecanemab)?',
      'The only decision a patient can make to influence the cost of their infusion is to decide where to receive treatment. Generally, there are three options within the healthcare system where a patient may receive prescription drug infusion therapy from a healthcare professional:',
      '1. Hospital outpatient',
      '1. Home',
      '1. Office setting (ambulatory infusion center or specialty doctor\'s office)',
      'Hospital outpatient is where 50-60% of infusions take place nationally. The cost is generally ~2x what it costs in the home or office. Home infusion has received a lot of press recently, but according to the National Infusion Center Association, it tends to be 50% more expensive than a healthcare provider\'s office. The office setting will be the most affordable care setting for patients who have received a referral from their physician for infusion therapy.',
      '## How can I lower the cost of Leqembi (lecanemab) infusions?',
      'Eisai is in the process of establishing a Patient Assistance Program to provide Leqembi at no cost for eligible uninsured and underinsured patients who meet certain financial criteria.',
      '## How Local Infusion can help',
      'In the original article, Local Infusion described pairing each patient 1:1 with a Guide who works with you to determine out-of-pocket costs and which financial programs you may be eligible for, and who handles prior authorization. That description is about Local Infusion. Local Doctor does not operate those infusion centers. Questions about coverage for a Local Doctor eligibility review can start with [[intake|/get-started]].',
      'For questions regarding pricing and insurance, the original article said its team would work together to provide guidance on financial assistance support and help patients minimize costs where possible.',
      '### Read more about Leqembi',
      '- [[The Institute For Clinical and Economic Review (ICER) Publishes Final Evidence Report on Lecanemab For Alzheimer\'s Disease|https://icer.org/news-insights/press-releases/icer-publishes-final-evidence-report-on-lecanemab-for-alzheimers-disease/]]',
      '- [[Leqembi (Lecanemab) Is Now Approved For Alzheimer\'s Treatment: What To Know|/blog/leqembi-infusion]]',
      '- [[Leqembi vs Aduhelm For Alzheimer\'s: What\'s The Difference?|/blog/lecanemab-vs-aducanumab]]',
      '- [[Leqembi vs Donanemab For Alzheimer\'s: What\'s The Difference?|/blog/donanemab-vs-lecanemab]]',
      ...eligibilityCta,
    ],
  },
  {
    slug: 'donanemab-vs-lecanemab',
    title: 'Leqembi (Lecanemab) vs Donanemab For Alzheimer\'s: What\'s The Difference?',
    label: 'Treatment',
    excerpt: 'A comparison of lecanemab and donanemab: targets, dosing, approval status as originally reported, efficacy, cost, timing, and ARIA.',
    author: 'Jenna Paladino, NP',
    published: '2023-08-30',
    updated: '2024-11-10',
    canonicalUrl: 'https://mylocalinfusion.com/donanemab-vs-lecanemab/',
    blocks: [
      'Dive into the differences between Leqembi (lecanemab) and donanemab to better determine which is best for you.',
      'Alzheimer\'s disease continues to pose a significant healthcare challenge, which has led to the relentless search for effective Alzheimer\'s drugs. According to the [[National Institute on Aging and the Alzheimer\'s Association Research Framework|https://jamanetwork.com/journals/jama/fullarticle/2807533#joi230087r3]], abnormal β-amyloid is a key pathological hallmark of Alzheimer\'s disease. β-amyloid, also known as beta-amyloid, is a protein fragment that tends to accumulate and form sticky plaques outside the neurons of the brain. The accumulation of this plaque disrupts communication between neurons, which is why it\'s one of the major targets in Alzheimer\'s disease drug development. Leqembi (lecanemab) and donanemab are two such medications that help with early-stage Alzheimer\'s disease. Below, we dive into the differences between these two drugs to help you better determine which is best for you.',
      '## About lecanemab',
      'Manufactured by Biogen and Eisai, lecanemab is a monoclonal antibody that targets soluble aggregated Aβ species such as monomers, oligomers, insoluble fibrils in plaques, and protofibrils. Soluble aggregated Aβ species are forms of β-amyloid (Aβ) peptides that have the tendency to clump together and form aggregates, leading to the formation of insoluble plaques in the brains of those with Alzheimer\'s disease. [[Research has shown|https://alzres.biomedcentral.com/articles/10.1186/s13195-022-01124-2]] that lecanemab is effective in reducing robust brain fibrillar amyloid and slowing clinical decline in early Alzheimer\'s disease ("early" meaning mild cognitive impairment or mild dementia).',
      'Read more: [[Leqembi (Lecanemab) Is Now Approved For Alzheimer\'s Treatment: What To Know|/blog/leqembi-infusion]].',
      '## About donanemab',
      'Donanemab (N3pG) is a monoclonal antibody that recognizes the Aβ found in amyloid plaques. Unlike other Alzheimer\'s medications that work to prevent the deposition of new plaques or the growth of existing plaques, donanemab targets the deposited plaque and works to clear the existing amyloid plaques in the brain.',
      '## Top-line differences between lecanemab and donanemab',
      'While donanemab and lecanemab are both monoclonal antibodies that target amyloid-beta (Aβ) plaques, the main difference is that they target them at different stages as they build up in the brain. Lecanemab targets amyloid-beta (Aβ) plaques as it proceeds to form fibers, whereas donanemab binds itself to the plaques when the fibers have clumped together to become a larger plaque in the brain.',
      'Another major difference between these two medications is that, although they are both given as intravenous infusions based on the weight of the patients, lecanemab is given every 2 weeks while donanemab is given every 4 weeks.',
      '## Are both lecanemab and donanemab FDA-approved?',
      'The U.S. Food and Drug Administration approved lecanemab in January 2023 for the treatment of Alzheimer\'s disease through the Accelerated Approval Pathway, which expedites the approval of medications for a serious medical condition with unmet treatment needs.',
      'Although Eli Lilly\'s donanemab has been [[found effective for reducing amyloid plaque|https://pubmed.ncbi.nlm.nih.gov/37459141/]] in the early stages of Alzheimer\'s disease — and the FDA considers amyloid plaque reduction to be a valid Alzheimer\'s biomarker — the original article states that the medication has not yet received FDA approval. Approval status can change after publication. Confirm the current label with a licensed clinician.',
      '## Efficacy: Does lecanemab work as well as donanemab?',
      'In the phase 3 trials for early Alzheimer\'s disease, [[CLARITY-AD for lecanemab|https://pubmed.ncbi.nlm.nih.gov/36544184/]] and [[TRAILBLAZER-ALZ 2 for donanemab|https://pubmed.ncbi.nlm.nih.gov/37459141/]], it was found that these two medications resulted in the slowing of cognitive decline and positive alterations on specific biomarkers of Alzheimer\'s disease.',
      'According to [[results from a landmark study|https://clinicaltrials.gov/ct2/show/NCT03367403]], Eli Lilly\'s donanemab slowed cognitive and functional decline in Alzheimer\'s patients by 35%. This was measured using the Integrated Alzheimer\'s Disease Rating Scale (iADRS).',
      '[[Results from Eisai and Biogen\'s lecanemab trial|https://clinicaltrials.gov/ct2/show/NCT01767311]] show that it reduces the rate of Alzheimer\'s disease by 27%.',
      '## What is the cost difference between lecanemab and donanemab?',
      'Lecanemab [[costs $26,500 per year|https://media-us.eisai.com/2023-01-06-EISAIS-APPROACH-TO-U-S-PRICING-FOR-LEQEMBI-TM-LECANEMAB-,-A-TREATMENT-FOR-EARLY-ALZHEIMERS-DISEASE,-SETS-FORTH-OUR-CONCEPT-OF-SOCIETAL-VALUE-OF-MEDICINE-IN-RELATION-TO-PRICE-OF-MEDICINE]].',
      'Since donanemab was not yet on the market when this article was written, the original said there was not a specific price for it yet, but there were speculations by the manufacturers that it would likely be around the same price as lecanemab.',
      '## How long it takes for lecanemab and donanemab to work',
      'According to [[lecanemab\'s Phase 3 trial|https://pubmed.ncbi.nlm.nih.gov/36544184/]], amyloid reduction is achieved within 3 months of treatment and clinical benefits within 6 months of treatment. In the research, more than 80% of subjects were amyloid negative (by visual reading) within 12–18 months of treatment in comparison to the placebo treatment.',
      'Research [[shows that|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC9468959/]], in early Alzheimer\'s disease, donanemab resulted in a decrease of amyloid plaque by 24 weeks, and [[68% of those who received donanemab|https://pubmed.ncbi.nlm.nih.gov/37459141/]] were "amyloid-negative" — meaning their amyloid plaque level was below 24.1 CL (complete amyloid clearance) — by the 76-week mark.',
      '## Side effects of lecanemab and donanemab',
      '### Side effects of lecanemab',
      '### Infusion-related reactions',
      'Lecanemab may result in [[severe reactions during or after infusion|https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761269s001lbl.pdf]], including:',
      '- Chills',
      '- Fever',
      '- Lightheadedness or dizziness',
      '- Nausea',
      '- Vomiting',
      '- Racing heart or chest pounding',
      '- Shortness of breath or difficulty breathing',
      '- Joint pain',
      '- Body aches',
      'You should inform your healthcare provider if you experience any of the above reactions. Your doctor may also give you medications that may prevent a reaction before starting the treatment.',
      '### Serious side effects',
      'Lecanemab [[may cause|https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761269s001lbl.pdf]] serious side effects like amyloid-related imaging abnormalities, or "ARIA." ARIA is an adverse event that manifests in two distinct types:',
      '1. ARIA-E, characterized by parenchymal or pial edema',
      '1. ARIA-hemorrhage (ARIA-H), which involves hemosiderin deposition in the form of superficial siderosis or hemorrhage',
      'It is mostly seen as temporary swelling in some parts of the brain which resolves over time. Some patients may have small spots of bleeding in or on the surface of their brain, and sometimes there might be larger areas of brain bleeding. Patients who experience this type of swelling in their brain are typically asymptomatic. If ARIA is symptomatic, signs and symptoms may include:',
      '- Headache',
      '- Confusion',
      '- Difficulty walking',
      '- Dizziness',
      '- Seizures',
      '- Vision changes',
      'Having the genetic risk factor (homozygous apolipoprotein E gene carriers) may result in an increased risk for experiencing ARIA. There are also medications that can increase the risk for larger areas of bleeding in the brain in patients receiving lecanemab. Your healthcare provider will check to see if you are on any medications that may increase the risk and also carry out magnetic resonance imaging (MRI) scans before and frequently throughout your treatment to check for ARIA.',
      '### Side effects of donanemab',
      'Patients may experience infusion-related reactions when receiving donanemab, but the original article said the specific reactions it may cause had not been disclosed yet. According to its trial, donanemab may result in changes in the brain known as amyloid-related imaging abnormalities (ARIA) which can be discovered through an MRI. In the [[TRAILBLAZER-ALZ|https://pubmed.ncbi.nlm.nih.gov/37459141/]] clinical trial results, 38.9% of patients had amyloid-related imaging abnormalities. In the clinical trial, 27.5% of the patients who received donanemab experienced ARIA-E while 30.5% had ARIA-H. There was also a 0.8% incidence of ARIA-E in the placebo group and a 7.2% incidence of ARIA-H in the placebo group.',
      '## Safety: Is lecanemab a safe alternative to donanemab and vice-versa?',
      'In the phase 3 trials, the reported rates of ARIA were slightly higher [[for donanemab|https://molecularneurodegeneration.biomedcentral.com/articles/10.1186/s13024-023-00637-0#ref-CR1]] (ARIA-E 24.0%, ARIA-H 31.4%) compared [[to lecanemab|https://molecularneurodegeneration.biomedcentral.com/articles/10.1186/s13024-023-00637-0#ref-CR2]] (ARIA-E 12.6%, ARIA-H 17.3%).',
      'Read more: [[Leqembi (Lecanemab) vs Aduhelm (Aducanumab) For Alzheimer\'s: What\'s The Difference?|/blog/lecanemab-vs-aducanumab]].',
      ...eligibilityCta,
    ],
  },
  {
    slug: 'lecanemab-vs-aducanumab',
    title: 'Leqembi (Lecanemab) vs Aduhelm (Aducanumab) For Alzheimer\'s: What\'s The Difference?',
    label: 'Treatment',
    excerpt: 'How lecanemab and aducanumab differ in target, approval pathway, efficacy, price, timing, and ARIA, as originally published by Local Infusion.',
    author: 'Jenna Paladino, NP',
    published: '2023-08-24',
    updated: '2024-11-10',
    canonicalUrl: 'https://mylocalinfusion.com/lecanemab-vs-aducanumab/',
    blocks: [
      'Discover the differences between these two drugs to better determine which is best for you.',
      'Alzheimer\'s disease is a debilitating condition that affects millions of people. According to the [[National Institute on Aging and the Alzheimer\'s Association Research Framework|https://jamanetwork.com/journals/jama/fullarticle/2807533#joi230087r3]], abnormal β-amyloid is a key pathological hallmark of Alzheimer\'s disease. β-amyloid, also known as beta-amyloid, is a protein fragment that tends to accumulate and form sticky plaques outside the neurons of the brain. The accumulation disrupts communication between neurons, which is why it\'s one of the major targets in Alzheimer\'s disease drug development. Leqembi (lecanemab) and Aduhelm (aducanumab) don\'t cure or reverse Alzheimer\'s disease, but they are anti-amyloid treatments that reduce the presence of beta-amyloid plaques in the brain.',
      'Below, we dive into the differences between these two drugs to help you better determine which is best for you.',
      '## About lecanemab',
      'Manufactured by Biogen and Eisai, lecanemab is a monoclonal antibody that targets a structure of a beta-amyloid called N3pG, which [[helps in the formation of amyloid plaques|https://alzres.biomedcentral.com/articles/10.1186/s13195-022-01124-2]] in the brain.',
      'Lecanemab targets soluble aggregated Aβ species such as monomers, oligomers, insoluble fibrils in plaques, and protofibrils. Soluble aggregated Aβ species are forms of β-amyloid (Aβ) peptides that have the tendency to clump together and form aggregates, leading to the formation of insoluble plaques in the brains of those with Alzheimer\'s disease.',
      '[[Research has shown|https://alzres.biomedcentral.com/articles/10.1186/s13195-022-01124-2]] that lecanemab is effective in reducing robust brain fibrillar amyloid and slowing clinical decline in early Alzheimer\'s disease ("early" meaning mild cognitive impairment or mild dementia).',
      '## About aducanumab',
      'Aducanumab is an amyloid beta-directed monoclonal antibody. It [[was found effective|https://www.ncbi.nlm.nih.gov/books/NBK573062/]] in people living with early Alzheimer\'s disease, mild cognitive impairment (MCI), or mild dementia due to Alzheimer\'s disease, or those with amyloid plaques buildup in their brain.',
      '## Top-line differences between lecanemab and aducanumab',
      'The main difference between lecanemab and aducanumab is that lecanemab primarily focuses on Aβ protofibrils, while aducanumab focuses on highly aggregated forms of Aβ. Another major difference is with their mechanism of action. Aducanumab removes beta-amyloid from the brain while lecanemab blocks the formation of amyloid plaques in the brain.',
      '## Are both lecanemab and aducanumab FDA-approved?',
      'Lecanemab and aducanumab have both received approval from the US Food and Drug Administration (FDA).',
      'In 2021, the FDA approved aducanumab through the Accelerated Approval Pathway.',
      '[[In January 2023, lecanemab received FDA approval|https://mylocalinfusion.com/leqembi-infusion/]] based on [[Clarity AD|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10119064/]], where lecanemab met the primary endpoint and all key secondary endpoints with statistically significant results. "Endpoint" here refers to the specific outcome or result that was used to assess the effectiveness of a medication during a clinical trial. Lecanemab was also approved through the Accelerated Approval Pathway. A Local Doctor copy of that Leqembi overview is at [[/blog/leqembi-infusion|/blog/leqembi-infusion]].',
      '## Efficacy: Does lecanemab work as well as aducanumab?',
      'Aducanumab [[showed significant slowing of cognitive decline|https://pubmed.ncbi.nlm.nih.gov/34515750]] in patients with early-stage disease in one of two of the phase 3 clinical trials.',
      'Lecanemab has a [[comparable efficacy|https://pubmed.ncbi.nlm.nih.gov/36449413]] as aducanumab, as measured by the Clinical Dementia Rating-Sum of Boxes (CDR-SB). This is the measurement tool used in clinical trials to assess the severity of dementia in individuals with Alzheimer\'s disease and other forms of dementia.',
      'One of the reasons why lecanemab [[is beneficial|https://pubmed.ncbi.nlm.nih.gov/36253511]] is its binding profile. Lecanemab [[focuses on targeting Aβ protofibrils|https://pubmed.ncbi.nlm.nih.gov/36253511]], while aducanumab and other medications like gantenerumab target highly aggregated forms of Aβ. This different target focus makes lecanemab [[more effective and safer|https://pubmed.ncbi.nlm.nih.gov/36253511/]] — lecanemab results in a substantially lower incidence of amyloid-related imaging abnormalities such as transient immunotherapy-related brain oedema and microbleeds.',
      '## What is the cost difference between lecanemab and aducanumab?',
      'Lecanemab [[costs $26,500|https://media-us.eisai.com/2023-01-06-EISAIS-APPROACH-TO-U-S-PRICING-FOR-LEQEMBI-TM-LECANEMAB-,-A-TREATMENT-FOR-EARLY-ALZHEIMERS-DISEASE,-SETS-FORTH-OUR-CONCEPT-OF-SOCIETAL-VALUE-OF-MEDICINE-IN-RELATION-TO-PRICE-OF-MEDICINE]] for a year\'s worth of treatment while aducanumab costs [[$28,200|https://investors.biogen.com/news-releases/news-release-details/biogen-announces-reduced-price-aduhelmr-improve-access-patients]]. Keep in mind that the amount a patient eventually pays will depend on their insurance policies or whether they use services like Medicare.',
      '## How long it takes for lecanemab and aducanumab to work',
      'According to [[lecanemab\'s Phase 3 trial|https://pubmed.ncbi.nlm.nih.gov/36544184/]], amyloid reduction is achieved within 3 months of treatment and clinical benefits within 6 months of treatment. In the research, more than 80% of subjects were amyloid negative (by visual reading) within 12–18 months of treatment in comparison to the placebo treatment.',
      'According to [[aducanumab clinical trials|https://www.ncbi.nlm.nih.gov/books/NBK573062/]], it takes ~18 months to reduce amyloid plaque levels — although it\'s important to note that aducanumab is a long-term drug, so if it\'s effective your doctor may have you take it for a longer period.',
      '## Side effects of lecanemab and aducanumab',
      '### Side effects of lecanemab',
      '### Infusion-related reactions',
      'Lecanemab may result in [[severe reactions during or after infusion|https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761269s001lbl.pdf]], including:',
      '- Chills',
      '- Fever',
      '- Lightheadedness or dizziness',
      '- Nausea',
      '- Vomiting',
      '- Racing heart or chest pounding',
      '- Shortness of breath or difficulty breathing',
      '- Joint pain',
      '- Body aches',
      'You should inform your healthcare provider if you experience any of the above reactions. Your doctor may also give you medications that may prevent a reaction before starting the treatment.',
      '### Serious side effects',
      'Lecanemab [[may cause|https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761269s001lbl.pdf]] serious side effects like amyloid-related imaging abnormalities, or "ARIA." ARIA is an adverse event that manifests in two distinct types:',
      '1. ARIA-E, characterized by parenchymal or pial edema',
      '1. ARIA-hemorrhage (ARIA-H), which involves hemosiderin deposition in the form of superficial siderosis or hemorrhage',
      'It is mostly seen as temporary swelling in some parts of the brain which resolves over time. Some patients may have small spots of bleeding in or on the surface of their brain, and sometimes there might be larger areas of brain bleeding. Patients who experience this type of swelling in their brain are typically asymptomatic. If ARIA is symptomatic, signs and symptoms may include:',
      '- Headache',
      '- Confusion',
      '- Difficulty walking',
      '- Dizziness',
      '- Seizures',
      '- Vision changes',
      'Having the genetic risk factor (homozygous apolipoprotein E gene carriers) may result in an increased risk for experiencing ARIA. There are also medications that can increase the risk for larger areas of bleeding in the brain in patients receiving lecanemab. Your healthcare provider will check to see if you are on any medications that may increase the risk and also carry out magnetic resonance imaging (MRI) scans before and during your treatment to check for ARIA.',
      '### Side effects of aducanumab',
      '### Mild side effects',
      'Aducanumab may cause some mild side effects, including:',
      '- Headache',
      '- Diarrhea',
      '- Upper respiratory tract infection',
      '- Confusion',
      '- Disorientation',
      'These side effects may stop within a few days or a couple of weeks.',
      '### Serious allergic reactions',
      'Aducanumab may cause some serious allergic reactions during or after an infusion, including:',
      '- Hives',
      '- Swelling of the face, mouth, lips, or tongue',
      'You should inform your healthcare provider if you experience any of the symptoms of a serious allergic reaction during or after an infusion. Also, during an aducanumab infusion, hypersensitivity reactions such as angioedema or urticaria may occur, in which case your provider will immediately discontinue treatment.',
      '### Serious side effects of aducanumab',
      'Aducanumab may also cause ARIA. To ensure your safety during aducanumab treatment, your healthcare provider will conduct baseline magnetic resonance imaging (MRI) scans before you start and periodic MRI scans during the course of treatment to monitor any potential occurrence of ARIA.',
      '## Safety: is lecanemab a safe alternative to aducanumab and vice-versa?',
      'There is a substantially [[lower incidence of amyloid-related imaging abnormalities|https://pubmed.ncbi.nlm.nih.gov/36253511]] with lecanemab. This is because lecanemab mainly targets Aβ protofibrils, while aducanumab and other medications like gantenerumab targets highly aggregated forms of Aβ.',
      ...eligibilityCta,
    ],
  },
  {
    slug: 'leqembi-infusion',
    title: 'Leqembi (Lecanemab) Is Now Approved For Alzheimer\'s Treatment: What To Know',
    label: 'Treatment',
    excerpt: 'How Leqembi works, who it is prescribed for, what Clarity AD reported, how it is given, and the side effects the label describes.',
    author: 'Jenna Paladino, NP',
    published: '2023-08-17',
    updated: '2024-11-10',
    canonicalUrl: 'https://mylocalinfusion.com/leqembi-infusion/',
    blocks: [
      'The FDA\'s full approval of Leqembi (lecanemab-irmb) has made it one of the few infusions that can be used for Alzheimer\'s disease. Continue reading to learn more about how Leqembi works and what makes it different from other Alzheimer\'s drugs.',
      '## What is Leqembi?',
      'Leqembi is an intravenous (IV) infusion prescribed for early Alzheimer\'s disease. It contains the active drug lecanemab-irmb and is used to slow the progression of Alzheimer\'s disease in patients who have mild cognitive impairment or mild dementia — meaning those who are still in the early stages of dementia or who are experiencing some cognitive defects that do not significantly impair their daily lives.',
      'Alzheimer\'s disease results from an accumulation of beta-amyloid plaques in the brain, which damage nerve cells. Leqembi belongs to the amyloid beta-directed monoclonal antibodies drug class and works to slow the decline of Alzheimer\'s disease in its early stages by reducing the buildup of these plaques.',
      '## When was Leqembi approved by the U.S. Food and Drug Administration (FDA)?',
      'On January 6, 2023, Leqembi received full FDA approval through the Accelerated Approval pathway for the treatment of Alzheimer\'s disease after meeting its primary and secondary endpoints with [[statistically significant results|https://classic.clinicaltrials.gov/ct2/show/NCT03887455]] ("endpoint" here refers to the specific outcome or result that was used to assess the effectiveness of a medication during a clinical trial). It joined the new wave of medications that targets the fundamental pathophysiology of Alzheimer\'s disease and have received traditional approval, including Aduhelm (aducanumab).',
      'As a recently authorized medication, Leqembi may not be widely available yet since many facilities, particularly those that don\'t specialize in infusion therapy, often take longer to add a new drug into their formulary.',
      '## Is Leqembi offered at Local Infusion?',
      'The original article says yes: Local Infusion wrote that it was ready to offer Leqembi at all of its infusion-center locations once a patient was referred. Local Doctor does not operate infusion centers. If you are trying to find out whether a specialist should review treatment eligibility, [[start with intake|/get-started]]. Any treatment decision still belongs to a licensed clinician.',
      '## How does Leqembi work?',
      'Although research hasn\'t fully uncovered the specific causes of Alzheimer\'s disease, typically it is recognized by alterations in the brain. These alterations include the presence of amyloid beta plaques and neurofibrillary (tau) tangles, which lead to the loss of neurons and their connections. This pathological process significantly impacts a person\'s memory and cognitive abilities. Leqembi [[works by reducing amyloid beta plaques|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10040446]] in the brain which, in turn, slows down the progression of Alzheimer\'s disease.',
      'Read more:',
      '- [[Leqembi (Lecanemab) vs Aduhelm (Aducanumab) For Alzheimer\'s: What\'s The Difference?|/blog/lecanemab-vs-aducanumab]]',
      '- [[Leqembi (Lecanemab) vs Donanemab For Alzheimer\'s: What\'s The Difference?|/blog/donanemab-vs-lecanemab]]',
      '## What is the success rate of Leqembi?',
      'In 2022, researchers from Eisai and Biogen (the manufacturers of Leqembi) published the results of [[Clarity AD|https://clinicaltrials.gov/ct2/show/NCT03887455]] (the phase 3 clinical trial) in [[The New England Journal of Medicine|https://www.nejm.org/doi/full/10.1056/NEJMoa2212948]], which showed that, in comparison with a placebo, Leqembi slowed down the rate of cognitive decline and reduced the buildup of amyloid beta plaques by approximately 59.1 centiloids (a unit used to measure the extent of amyloid burden in the brain).',
      '### On reducing amyloid-β levels',
      'Leqembi [[demonstrated efficacy|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10040446]] in reducing brain amyloid-β levels. In an over 18-month period of Leqembi treatment, approximately 68% of the treated patients exhibited complete removal of amyloid-β from their brains. This was confirmed through the use of amyloid positron-emission tomography (PET) imaging, a brain imaging technique.',
      '### On reducing tau',
      'At the same time, measurements of "plasma markers of phospho-tau species," substances present in the blood which was carried out by PET and cerebrospinal fluid (CSF) biomarkers of Alzheimer\'s disease, showed comparable reductions to those observed in brain amyloid-β levels. Thus, it is possible that Leqembi might also be impactful on tau, a substance related to amyloid-β and which is closely associated with the cognitive decline and memory loss seen in Alzheimer\'s disease.',
      'One of the potential reasons why Leqembi had a high success rate was [[due to the fact that it targeted amyloid-β better|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10040446]] than other treatments for Alzheimer\'s disease. However, it does come with certain limitations, the most notable of which is that [[it can\'t address cognitive impairment in older ages|https://www.ncbi.nlm.nih.gov/pmc/articles/PMC10040446]].',
      '## How long does treatment with Leqembi take?',
      'The prescribed dose for Leqembi is 10 mg/kg, which should be diluted and administered as an intravenous infusion lasting about 1 hour. This infusion is administered once every 2 weeks. If a scheduled infusion is missed, it\'s important that a patient receives the subsequent dose as soon as possible.',
      'Also, it is important to confirm the presence of amyloid beta pathology before receiving Leqembi.',
      '## What are the potential side effects of Leqembi?',
      '### Infusion-related reactions',
      'According to Leqembi\'s [[prescribing information|https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761269s001lbl.pdf]], it may cause reactions in patients either during the infusion or shortly after. For this reason, there is a recommended observation time following Leqembi infusions, during which you will be monitored by your infusion provider for any signs or symptoms of reaction. Some of the infusion-related reactions a patient may experience include:',
      '- Chills',
      '- Body aches',
      '- Joint pain',
      '- Fever',
      '- Shortness of breath',
      '- Lightheadedness',
      '- Racing heart rate',
      'If you experience any of the above symptoms, inform your healthcare providers or caregivers immediately. Your provider may also administer allergy medicines, anti-inflammatory medicines, or steroids to help prevent infusion-related reactions.',
      '### Serious side effects',
      '### Amyloid ARIA',
      'Leqembi [[can cause|https://www.accessdata.fda.gov/drugsatfda_docs/label/2023/761269s001lbl.pdf]] serious side effects like amyloid related imaging abnormalities (ARIA) — ARIA with edema (ARIA-E) or ARIA with hemosiderin deposition (ARIA-H). While this serious, life-threatening side effect is typically asymptomatic and only detectable on brain MRIs, potential symptoms may include:',
      '- Vision changes',
      '- Seizures',
      '- Dizziness',
      '- Headache',
      '- Nausea',
      '- Confusion',
      '- Difficulty walking',
      'ARIA commonly occurs as temporary brain swelling that resolves over time. Some patients may experience brain bleeding in small spots, and in some rare occasions brain bleeding can occur in larger areas of the brain. Some have a genetic risk factor (ApoE ε4 homozygotes) that may cause them to have an increased risk for ARIA. Talk to your healthcare professionals about testing for ApoE ε4 status before you begin Leqembi.',
      'Some medications (for example, anticoagulant medication and supplements) can increase a patient\'s risk for larger areas of brain bleeding. It\'s important to inform your healthcare provider of all the medications and supplements you\'re on so they can check if any increase your risk of ARIA. Your healthcare provider will also do magnetic resonance imaging (MRI) scans prior to the start of your treatment and during your treatment to check for ARIA.',
      '### Intracerebral hemorrhage',
      'Another neurological side effect of Leqembi is serious intracerebral hemorrhage, which is a type of stroke that occurs when a blood vessel ruptures and bleeds into the brain tissue.',
      '## How much does Leqembi cost?',
      'Leqembi by Eisai Inc and Biogen Inc (BIIB.O) has an annual [[list price of $26,500|https://media-us.eisai.com/2023-01-06-EISAIS-APPROACH-TO-U-S-PRICING-FOR-LEQEMBI-TM-LECANEMAB-,-A-TREATMENT-FOR-EARLY-ALZHEIMERS-DISEASE,-SETS-FORTH-OUR-CONCEPT-OF-SOCIETAL-VALUE-OF-MEDICINE-IN-RELATION-TO-PRICE-OF-MEDICINE]]. However, the actual out-of-pocket amount of each patient will vary depending on their individual insurance coverage and their usage of Medicare and Medicaid services. Be sure to inquire about co-pay assistance if cost is of concern to you as many patients will qualify for additional assistance and even $0 copay depending on eligibility. This program is sponsored by Eisai Inc.',
      'Read more: [[How Much Does Leqembi (Lecanemab) Cost?|/blog/leqembi-lecanemab-cost]]',
      ...eligibilityCta,
    ],
  },
]

export function getBlogPost(slug: string) {
  return blogPosts.find((post) => post.slug === slug)
}
